import Header from "./_components/header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Nepali Voice Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-screen flex flex-col text-slate-800 antialiased">
      <Header />
      {children}
    </div>
  );
}
